# -*- coding: utf-8 -*-
"""forsati_final (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yZhRjBQtQXjh6-hnI-zUTeeP-4LzKbl7

# Forsati Business Success Model — Final Updated Version
"""

import pandas as pd
import numpy as np
from xgboost import XGBClassifier
from difflib import get_close_matches

from sklearn.model_selection import (
    GroupKFold, cross_val_score, cross_val_predict, RandomizedSearchCV
)
from sklearn.preprocessing import LabelEncoder
from sklearn.calibration import CalibratedClassifierCV
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.inspection import permutation_importance

import warnings
warnings.filterwarnings('ignore')

"""## 1. Load Data"""

df = pd.read_csv('forsati_final_dataset.csv')
print(f'Shape: {df.shape}')
print(f'NaN in success column: {df["success"].isna().sum()}')
df.head()

"""## 2. Encoding"""

# Category label encoding
le = LabelEncoder()
df['category_encoded'] = le.fit_transform(df['category_en'])

# Region one-hot encoding
region_map = {0: 'Central', 1: 'East', 2: 'North', 3: 'South', 4: 'West'}
df['region'] = df['region_encoded'].map(region_map)
region_dummies = pd.get_dummies(df['region'], prefix='region')
df = pd.concat([df, region_dummies], axis=1)

# Target encoding for neighborhood (mean success rate per neighborhood)
neighborhood_success_rate = df.groupby('neighborhood')['success'].mean()
df['neighborhood_success_rate'] = df['neighborhood'].map(neighborhood_success_rate)
df['neighborhood_success_rate'] = df['neighborhood_success_rate'].fillna(df['success'].mean())

# Target encoding for category
category_success_rate = df.groupby('category_en')['success'].mean()
df['category_success_rate'] = df['category_en'].map(category_success_rate)
df['category_success_rate'] = df['category_success_rate'].fillna(df['success'].mean())

print('Encoding done.')

"""## 3. Feature Engineering"""

# Market saturation: share of this category among all businesses
df['category_share'] = df['category_count'] / (df['total_businesses'] + 1)

# Demand-supply: population per business
df['pop_per_business'] = df['Population'] / (df['total_businesses'] + 1)

# Transport accessibility index
df['transport_index'] = df['metro'] + df['bus'] + df['public_station']

# Nearby competition density
df['nearby_competition_density'] = df['nearby_same_category'] / (df['nearby_all_businesses'] + 1)

# Economic activity proxy
df['economic_index'] = df['annual_transactions'] / (df['Population'] + 1)

# Population density per km2
df['pop_density_per_km2'] = df['Population'] / (df['Area_km2'] + 0.01)

print('Feature engineering done.')

"""## 4. Define Features & Clean Data"""

feature_cols = [
    # Original features
    'category_encoded',
    'category_count',
    'total_businesses',
    'competition_ratio',
    'nearby_same_category',
    'nearby_all_businesses',
    'population_density',
    'avg_price_m2',
    'business_licenses',
    'street_count',
    'annual_transactions',
    'Population',
    'Area_km2',
    'metro',
    'bus',
    'public_station',

    # Target-encoded features
    'neighborhood_success_rate',
    'category_success_rate',

    # Engineered features
    'category_share',
    'pop_per_business',
    'transport_index',
    'nearby_competition_density',
    'economic_index',
    'pop_density_per_km2',
]

# Add one-hot region columns
feature_cols += list(region_dummies.columns)

X = df[feature_cols]
y = df['success']

# --- Drop rows where target (y) is NaN ---
valid_mask   = y.notna()
X_clean      = X[valid_mask].reset_index(drop=True)
y_clean      = y[valid_mask].astype(int).reset_index(drop=True)
groups_clean = df.loc[valid_mask, 'neighborhood'].reset_index(drop=True)

print(f'Total rows: {len(df)}')
print(f'Dropped {(~valid_mask).sum()} rows with NaN in success column.')
print(f'Remaining rows: {len(y_clean)}')
print(f'Class balance — 0: {(y_clean==0).sum()}, 1: {(y_clean==1).sum()}')

"""## 5. Hyperparameter Tuning"""

# Automatic class imbalance handling
neg_count = (y_clean == 0).sum()
pos_count = (y_clean == 1).sum()
spw = neg_count / pos_count if pos_count > 0 else 1
print(f'scale_pos_weight = {spw:.2f}')

param_dist = {
    'n_estimators':     [100, 200, 300, 500],
    'max_depth':        [3, 4, 5, 6, 7],
    'learning_rate':    [0.01, 0.05, 0.1, 0.15],
    'subsample':        [0.6, 0.7, 0.8, 0.9, 1.0],
    'colsample_bytree': [0.5, 0.6, 0.7, 0.8, 1.0],
    'min_child_weight': [1, 3, 5, 7],
    'gamma':            [0, 0.1, 0.2, 0.5],
    'reg_alpha':        [0, 0.01, 0.1, 1],
    'reg_lambda':       [1, 1.5, 2, 5],
}

base_xgb = XGBClassifier(
    random_state=42,
    eval_metric='logloss',
    scale_pos_weight=spw,
    tree_method='hist',
)

# GroupKFold: no shuffle or random_state arguments
cv_group = GroupKFold(n_splits=5)

search = RandomizedSearchCV(
    base_xgb,
    param_distributions=param_dist,
    n_iter=30,
    scoring='f1',
    cv=cv_group,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

search.fit(X_clean, y_clean, groups=groups_clean)
print(f'\nBest F1 score: {search.best_score_:.4f}')
print(f'Best params: {search.best_params_}')

"""## 6. Cross-Validation Evaluation"""

best_model = search.best_estimator_

for metric in ['accuracy', 'f1', 'roc_auc']:
    scores = cross_val_score(
        best_model, X_clean, y_clean,
        cv=cv_group, groups=groups_clean, scoring=metric
    )
    print(f'{metric:10s}: {scores.mean()*100:.2f}% ± {scores.std()*100:.2f}%')

y_pred = cross_val_predict(
    best_model, X_clean, y_clean,
    cv=cv_group, groups=groups_clean
)

print('\n=== Classification Report ===')
print(classification_report(y_clean, y_pred, target_names=['غير ناجح', 'ناجح']))
print('\n=== Confusion Matrix ===')
print(confusion_matrix(y_clean, y_pred))

"""## 7. Train Final Model with Probability Calibration"""

best_model.fit(X_clean, y_clean)

# Calibrate probabilities so predict_proba values are more reliable
calibrated_model = CalibratedClassifierCV(best_model, cv=5, method='isotonic')
calibrated_model.fit(X_clean, y_clean)

model = calibrated_model
print('Final calibrated model trained successfully.')

"""## 8. Feature Importance"""

perm = permutation_importance(
    model, X_clean, y_clean,
    n_repeats=5,
    random_state=42,
    scoring='f1'
)

perm_importances = pd.DataFrame({
    'العامل': feature_cols,
    'الأهمية': perm.importances_mean
}).sort_values('الأهمية', ascending=False)

print('\n=== Permutation Importance (F1-based) ===')
for _, row in perm_importances.iterrows():
    bar = '█' * max(0, int(row['الأهمية'] * 200))
    print(f"{row['العامل']:<35} {row['الأهمية']:+.4f}  {bar}")

"""## 9. Scoring & Recommendation Functions"""

def normalize_value(value, min_value, max_value):
    if max_value == min_value:
        return 0.5
    return max(0.0, min(1.0, (value - min_value) / (max_value - min_value)))


def show_suggestions(input_name, valid_names, title):
    suggestions = get_close_matches(input_name, valid_names, n=3, cutoff=0.4)
    print(f" {title} not found: '{input_name}'")
    if suggestions:
        print('Did you mean:')
        for s in suggestions:
            print(f'   - {s}')
    else:
        print('   No close match found.')


def build_candidate_row(df, category_name, neighborhood_name, feature_cols):
    valid_categories    = df['category_en'].dropna().unique()
    valid_neighborhoods = df['neighborhood'].dropna().unique()

    if category_name not in valid_categories:
        show_suggestions(category_name, valid_categories, 'Category')
        return None

    if neighborhood_name not in valid_neighborhoods:
        show_suggestions(neighborhood_name, valid_neighborhoods, 'Neighborhood')
        return None

    pair_rows         = df[(df['category_en'] == category_name) & (df['neighborhood'] == neighborhood_name)]
    neighborhood_rows = df[df['neighborhood'] == neighborhood_name]
    category_rows     = df[df['category_en'] == category_name]

    if len(pair_rows) > 0:
        base = pair_rows.mean(numeric_only=True)
    elif len(neighborhood_rows) > 0 and len(category_rows) > 0:
        # Blend neighborhood + category means for a better synthetic row
        base = (neighborhood_rows.mean(numeric_only=True) + category_rows.mean(numeric_only=True)) / 2
    elif len(neighborhood_rows) > 0:
        base = neighborhood_rows.mean(numeric_only=True)
    else:
        base = df.mean(numeric_only=True)

    row = pd.DataFrame([base])

    # Restore categorical encodings from actual data
    row['category_encoded']          = df[df['category_en'] == category_name]['category_encoded'].iloc[0]
    row['neighborhood_success_rate'] = neighborhood_success_rate.get(neighborhood_name, df['success'].mean())
    row['category_success_rate']     = category_success_rate.get(category_name, df['success'].mean())

    # Recompute transport_index to stay consistent
    if all(c in row.columns for c in ['metro', 'bus', 'public_station']):
        row['transport_index'] = row['metro'] + row['bus'] + row['public_station']

    for col in feature_cols:
        if col not in row.columns:
            row[col] = 0

    return row[feature_cols]


def recommendation_score(
    df,
    model,
    feature_cols,
    category_name,
    neighborhood_name,
    show_details=True
):
    row = build_candidate_row(df, category_name, neighborhood_name, feature_cols)
    if row is None:
        return None

    ml_probability = model.predict_proba(row)[0][1]
    values = row.iloc[0]

    demand_score = normalize_value(
        values['population_density'],
        df['population_density'].min(), df['population_density'].max()
    )

    nearby_activity_score = normalize_value(
        values['nearby_all_businesses'],
        df['nearby_all_businesses'].min(), df['nearby_all_businesses'].max()
    )

    transport_score = normalize_value(
        values['transport_index'],
        (df['metro'] + df['bus'] + df['public_station']).min(),
        (df['metro'] + df['bus'] + df['public_station']).max()
    )

    market_strength_score = normalize_value(
        values['business_licenses'],
        df['business_licenses'].min(), df['business_licenses'].max()
    )

    competition = values['competition_ratio']
    ideal_competition = df['competition_ratio'].median()
    if ideal_competition == 0:
        competition_score = 0.5
    else:
        competition_score = max(0.0, min(1.0,
            1 - abs(competition - ideal_competition) / ideal_competition
        ))

    final_score = (
        0.40 * ml_probability +
        0.20 * demand_score +
        0.15 * competition_score +
        0.10 * nearby_activity_score +
        0.10 * transport_score +
        0.05 * market_strength_score
    )
    final_score = round(final_score * 100, 2)

    if final_score >= 70:   label = 'مناسب جداً'
    elif final_score >= 50: label = 'مناسب'
    else:                   label = 'غير مناسب'

    if show_details:
        print('\n' + '=' * 55)
        print(f'التقييم الذكي لمشروع: {category_name.upper()}')
        print(f'الحي: {neighborhood_name}')
        print('=' * 55)
        print(f'النتيجة النهائية: {final_score}/100  {label}')
        print('-' * 55)
        print('تفاصيل التقييم:\n')
        print(f'    توقع النموذج:          {ml_probability * 100:6.1f}')
        print(f'    الطلب (الكثافة):       {demand_score * 100:6.1f}')
        print(f'     المنافسة:             {competition_score * 100:6.1f}')
        print(f'    النشاط القريب:         {nearby_activity_score * 100:6.1f}')
        print(f'    المواصلات:             {transport_score * 100:6.1f}')
        print(f'    قوة السوق:             {market_strength_score * 100:6.1f}')
        print('=' * 55)

    return {
        'category': category_name,
        'neighborhood': neighborhood_name,
        'final_score': final_score,
        'ml_probability': round(ml_probability * 100, 2),
        'demand_score': round(demand_score * 100, 2),
        'competition_score': round(competition_score * 100, 2),
        'nearby_activity_score': round(nearby_activity_score * 100, 2),
        'transport_score': round(transport_score * 100, 2),
        'market_strength_score': round(market_strength_score * 100, 2)
    }


def rank_neighborhoods(df, model, feature_cols, category_name, top_n=10):
    if category_name not in df['category_en'].dropna().unique():
        show_suggestions(category_name, df['category_en'].dropna().unique(), 'Category')
        return pd.DataFrame()

    neighborhoods = sorted(df['neighborhood'].dropna().unique())
    results = []

    for neighborhood in neighborhoods:
        score = recommendation_score(
            df, model, feature_cols, category_name, neighborhood, show_details=False
        )
        if score is not None:
            results.append(score)

    if not results:
        print('No results found.')
        return pd.DataFrame()

    results_df = pd.DataFrame(results).sort_values('final_score', ascending=False).reset_index(drop=True)

    print(f'\n=== أفضل {top_n} أحياء لـ {category_name} ===')
    print(f'{"#":<4} {"الحي":<22} {"الدرجة":<10} {"التقييم"}')
    print('-' * 52)
    for i, row in results_df.head(top_n).iterrows():
        s = row['final_score']
        if s >= 70:   lbl = 'مناسب جداً'
        elif s >= 50: lbl = 'مناسب'
        else:         lbl = 'غير مناسب'
        print(f'{i+1:<4} {row["neighborhood"]:<22} {s:<10.1f} {lbl}')

    return results_df

"""## 10. Example Usage"""

res = recommendation_score(df, model, feature_cols, 'cafe', 'النرجس')

res = recommendation_score(df, model, feature_cols, 'cafe', 'gf')

ranking = rank_neighborhoods(df, model, feature_cols, 'restaurant', 8)

ranking = rank_neighborhoods(df, model, feature_cols, 'cafe', 8)


"""import pickle

saved = {
    'model': model,
    'features': feature_cols
}

with open('forsati_model_v2.pkl', 'wb') as f:
    pickle.dump(saved, f)

print(' تم حفظ النموذج الجديد: forsati_model_v.pkl')"""